### ISSUE TITLE
Not sure how to stop the mouse after reaching finish tile

### ISSUE THREAD

**Issue by normal-crayon** [mackorone/mms#14]
im using python template and not able to stop the mouse after reaching the finish tile,i.e. its stilling running around the maze , i tried altering the source code but still not working.

**Comment by mackorone** [comment]
Hi, I'm happy to hear you're using the simulator! At a high level, your algorithm needs to keep track of the position of the mouse. If you want the mouse to stop when it reaches the center, you should stop issuing movement commands when that condition is met.

> still not working

What have you tried so far? What didn't work as expected?
