### ISSUE TITLE
mms Arduino API

### ISSUE THREAD

**Issue by GoGoCom** [mackorone/mms#15]
Hi! Mack!
There is an issue regarding moveForward() function as follow
bool moveForward() {
    return getAck("moveForward");
}
There is no argument for a distance.
I will appreciate so much if you fix .
Thanks Mack!
Kind regards
David

**Comment by mackorone** [comment]
You're right, the example Arduino API doesn't support a distance argument yet. Feel free to submit a pull request to that repo that adds the missing functionality!
