### ISSUE TITLE
32 x 32 maze support

### ISSUE THREAD

**Issue by GoGoCom** [mackorone/mms#16]
Hi! Mack!
I tried to use 32x32 maze but display an error message which is "invalid maze file".
Is there any other way to use ?
If I can use 32x32 maze, I will appreciate so much .
Thanks mack!
Kind regards
David

**Comment by mackorone** [comment]
@GoGoCom , what maze file did you use? What format is it? Are you sure it's a valid maze file? As far as I know, the simulator should support arbitrary maze dimensions.

**Comment by GoGoCom** [comment]
Hi! Mack!
Thank you for reply!
I tried to do 32x32 maze but it didn't work. I attached the num file I
tested.
Could you check it for me ? It might only work in 16x16 maze.

Thanks again
Have a good day!
Kind regards
GoGoCom

**Comment by mackorone** [comment]
@GoGoCom , did you mean to attach a file? Unless I"m missing something, nothing is attached.

**Comment by GoGoCom** [comment]
Yes I have attached the test file to this email.
test1.num

**Comment by GoGoCom** [comment]
Solved
