### ISSUE TITLE
Request for a new build

### ISSUE THREAD

**Issue by TJ178** [mackorone/mms#19]
Hey Mackorone,
I stumbled across this simulator recently when looking for viable simulators for my university's micromouse program. I've downloaded the latest release and got that working wonderfully, however I realized that the newest release doesn't include the addition of the second, easier to read and design map format. Would it be possible for you to create a new release with the the features that currently exist in the source code? I know it's a bit to ask but it would be great to have a link to send my students rather than figure out how to build it myself.

Thank you :)

**Comment by mackorone** [comment]
Thanks for your interest in the project! Yes, I can create a new release. Stay tuned.

**Comment by TJ178** [comment]
No worries, the earliest I'd need the new release is next Friday. Earlier would be better, but we're certainly not in a rush.

**Comment by mackorone** [comment]
v1.1.0 is available for download! Let me know if you run into any issues.
