### ISSUE TITLE
Unable to Build on garuda Linux

### ISSUE THREAD

**Issue by Spritan** [mackorone/mms#20]
I have tried building it from source as well as from aur, still no luck 
=>  Main issue seems to be "Project ERROR: Unknown module(s) in QT: openglwidgets"
=> I am unable to fing the install candidate  for openglwidgets

**Comment by mackorone** [comment]
What version of Qt are you using? How did you install it?

**Comment by mackorone** [comment]
@Spritan, thanks for the info. Unfortunately, it's still not enough for me to help with this issue. What have you tried so far? What errors did you encounter, specifically? Did searching Google turn up anything useful? Does the error occur only on your machine? Etc.

**Comment by Spritan** [comment]
Project ERROR: Unknown module(s) in QT: openglwidgets"
^ this was the issues that stopepd the build process.
I searcxhed that some qt moduole are needed to be manually installed explicitley but i was not able to find any install candidate for openglwidgets on arch or on ubuntu (which i use on distrobox)

**Comment by mackorone** [comment]
@Spritan based on this documentation, it's possible that `openglwidgets` module is deprecated in Qt 5.15 and replaced with `gui`: https://doc.qt.io/qt-5/qtopengl-index.html

Does it work if you just remove this line from `mms.pro`?
```
QT += openglwidgets
```

**Comment by Spritan** [comment]
Nope after removing 
`QT += openglwidgets`
This is what i have
`[🔴] × qmake && make                                                                                                                                                                     (base)
g++ -c -pipe -g -std=gnu++11 -D_REENTRANT -Wall -W -fPIC -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I../../miniconda3/include/qt -I../../miniconda3/include/qt/QtWidgets -I../../miniconda3/include/qt/QtGui -I../../miniconda3/include/qt/QtXml -I../../miniconda3/include/qt/QtCore -I../build/moc -I../../miniconda3/mkspecs/linux-g++ -o ../build/obj/Logging.o Logging.cpp
In file included from ../../miniconda3/include/qt/QtCore/qlocale.h:43,
from ../../miniconda3/include/qt/QtCore/qtextstream.h:46,
from ../../miniconda3/include/qt/QtCore/qdebug.h:49,
from ../../miniconda3/include/qt/QtCore/QDebug:1,
from Logging.h:3,
from Logging.cpp:1:
../../miniconda3/include/qt/QtCore/qvariant.h: In constructor ‘QVariant::QVariant(QVariant&&)’:
../../miniconda3/include/qt/QtCore/qvariant.h:265:25: warning: implicitly-declared ‘QVariant::Private& QVariant::Private::operator=(const QVariant::Private&)’ is deprecated [-Wdeprecated-copy]
265 |     { other.d = Private(); }
|                         ^
../../miniconda3/include/qt/QtCore/qvariant.h:380:16: note: because ‘QVariant::Private’ has user-provided ‘QVariant::Private::Private(const QVariant::Private&)’
380 |         inline Private(const Private &other) Q_DECL_NOTHROW
|                ^~~~~~~
Logging.cpp: In static member function ‘static void mms::Logging::handler(QtMsgType, const QMessageLogContext&, const QString&)’:
Logging.cpp:28:33: error: ‘endl’ is not a member of ‘Qt’
28 |     *STDOUT << formatted << Qt::endl;
|                                 ^~~~
Logging.cpp:28:33: note: suggested alternatives:
../../miniconda3/include/qt/QtCore/qtextstream.h:259:28: note:   ‘endl’
259 | Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
|                            ^~~~
In file included from /usr/include/c++/12.2.0/iostream:39,
from AssertMacros.h:3,
from Logging.cpp:3:
/usr/include/c++/12.2.0/ostream:688:5: note:   ‘std::endl’
688 |     endl(basic_ostream<_CharT, _Traits>& __os)
|     ^~~~
Logging.cpp:16:15: warning: unused parameter ‘type’ [-Wunused-parameter]
16 |     QtMsgType type,
|     ~~~~~~~~~~^~~~
make: *** [Makefile:2420: ../build/obj/Logging.o] Error 1`

**Comment by mackorone** [comment]
That's a new error - hooray!

That particular one is happening because `Qt::endl` was introduced in 5.14 (which makes me think you might not be using 5.15 after all). I think the error can be fixed by replacing `Qt::endl` with `endl`, e.g., https://github.com/bullet-physics-playground/bpp/issues/27

**Comment by P1n3appl3** [comment]
Thanks @csunwc, that patch (`s/openglwidgets/opengl`) fixes the [mms AUR package ](https://aur.archlinux.org/packages/mms-git).

**Comment by mackorone** [comment]
Thanks for the feedback, everyone! I made the suggested change - replacing `QT += openglwidgets` with `QT += opengl` - so I'm going to close this issue. Feel free to reopen if you're still running into problems.

**Comment by mackorone** [comment]
Update: I just realized I may have reintroduced this bug with https://github.com/mackorone/mms/commit/3ab04c1e2e933ef17946b7ccbfaf9c9641bb7529. If so, please comment here and we can figure out a resolution.

**Comment by mackorone** [comment]
@Soham-Bhanap, which version of Qt are you using? I believe it should work if you're using Qt 6. If not, can you please share an error message so that I can investigate? Thanks.
