### ISSUE TITLE
Running mms-cpp raises Uknown Error 

### ISSUE THREAD

**Issue by FallenDeity** [mackorone/mms#22]
Steps to reproduce

- [x] Clone this repository https://github.com/mackorone/mms-cpp
- [x] Filled same details as in [image](https://github.com/mackorone/mms-cpp/raw/master/config-windows.png)
- [x] Build Worked
- [x] Error when running

```
Process failed to start: Unknown error 0x000000c1.
```

Device Info
```
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
```
![mms 12-05-2023 15_29_20](https://github.com/mackorone/mms/assets/61227305/29de922d-86d0-42bd-8e2d-9b1723648048)

> **Note**  
> No issue when running program manually

**Comment by Blaze-Leo** [comment]
Seems like some dll libraries are probably missing. You can try this one, i just refreshed the dlls 
https://github.com/Blaze-Leo/mms/releases/tag/Original

**Comment by mackorone** [comment]
Thanks for submitting. To clarify, are you still hitting this issue?

**Comment by FallenDeity** [comment]
yeah works with python I tested it out issue arises when I use c++

**Comment by mackorone** [comment]
@FallenDeity and just to confirm: does your program work when invoked outside of the simulator?

**Comment by FallenDeity** [comment]
yeah its cloned from your repository mms-cpp i haven't touched a thing

**Comment by mackorone** [comment]
@FallenDeity can you send me a screenshot of you running the `mms-cpp` command from the command line, outside the context of the simulator? I want to see that it successfully starts, and that you can send it responses by writing to stdin. Something like this:

```
$./a.out
Running...
setColor 0 0 G
setText 0 0 abc
wallLeft
true  # <--- I entered this
wallFront
false  # <--- I entered this
moveForward
...
```

**Comment by FallenDeity** [comment]
![Uploading mms-cpp 24-05-2023 14_04_53.png…]()
Here it is

**Comment by mackorone** [comment]
So weird... Ok, I'll have to dig into this a little more. Thanks for reporting!

**Comment by hardliner66** [comment]
Googling the error brought up the following: https://stackoverflow.com/a/61080988

So there might be some CPU arch mismatch.

**Comment by mackorone** [comment]
Good find, @hardliner66. Based on that link and [this one](https://www.qtcentre.org/threads/45959-quot-Process-failed-to-start-quot-and-qprocess-generic-errors), I'm tempted to think that there's a compiler compatibility problem. Namely, the `g++` that's used to compile the program from *within* the simulator is somehow different from the compiler used *outside* of the simulator. Perhaps you can quickly verify that the binaries are the same by running `which g++` both inside and outside of the simulator? (I.e., set your build command to `which g++` and see what happens.)

**Comment by FallenDeity** [comment]
Dosn't seem to be the case I ran `where g++` equivalent of which for windows both point to same place my [mingw64](https://winlibs.com/) installation version `13.1.0` if that matters 
![Triyan Mukherjee 13-06-2023 14_23_38](https://github.com/mackorone/mms/assets/61227305/f09dd83b-6ac9-4394-968c-c92b9e434c7d)
![mms 13-06-2023 14_23_31](https://github.com/mackorone/mms/assets/61227305/daa68723-2efe-44cc-bec5-77368173f42b)

**Comment by mackorone** [comment]
This issue is pretty stale so I'm going to close it. Feel free to reopen it if the problem persists. (If not, I'd love to hear how you solved it!)
