### ISSUE TITLE
Rust api

### ISSUE THREAD

**Issue by hardliner66** [mackorone/mms#25]
I made a simple Rust API for MMS. If you want to mention it in your docs, that would be really nice.

https://crates.io/crates/mms-rs
https://github.com/hardliner66/mms-rs

**Comment by mackorone** [comment]
Wow, this is awesome! Thanks for adding Rust support. I just updated `README.md`: https://github.com/mackorone/mms/commit/eaa58f217d875014e204b23c660a2519a3a3fcb1

**Comment by hardliner66** [comment]
You're welcome. If you want ownership of the code, just let me know and I'll transfer everything to you :)
