### ISSUE TITLE
:-1: error: Unknown module(s) in QT: openglwidgets

### ISSUE THREAD

**Issue by jcocovich** [mackorone/mms#28]
I'm trying to build the micromouse simulator in Ubuntu 22 from downloaded source but the build command in QtCreator complains about openglwidgets. The build instructions are sufficiently vague to force me to ask for help. Reinstalling Qt with a different version was reported as being successful but that is garbage. Why does your simulator NOT even build in Linux???

**Comment by KenwoodFox** [comment]
Also haivng this problem, did you figure it out?

**Comment by mackorone** [comment]
@KenwoodFox What's your exact error message? What have you tried so far? Did Google help? Did ChatGPT help? What version of Qt are you using?

Just for bookkeeping, here's the commit that *may* be breaking things for you: https://github.com/mackorone/mms/commit/3ab04c1e2e933ef17946b7ccbfaf9c9641bb7529

**Comment by KenwoodFox** [comment]
Woah! That was quick! Turns out my issue was #20 it seems! Just making sure I can build locally before poking around!

```qmake --version
QMake version 3.1
Using Qt version 5.15.11 in /usr/lib```

**Comment by jcocovich** [comment]
:-1: error: Unknown module(s) in QT: openglwidgets
I just now downloaded the simulator project and selected Qt Creator 5 to get the above error message.

**Comment by mackorone** [comment]
@jcocovich I just uploaded a pre-compiled Linux binary [here](https://github.com/mackorone/mms/releases/tag/v1.2.0). Does it work for you? If not, feel free to reopen this issue.
