### ISSUE TITLE
After Updating to newest MacOS mms is unable to find the files

### ISSUE THREAD

**Issue by darugal** [mackorone/mms#30]
Updated to newest MacOS and opened mms and couldn't get it to run, haven’t changed a thing and I get this error:
execvp: No such file or directory

**Comment by mackorone** [comment]
@darugal what's "it"? Your algorithm? The simulator? Something else? What steps have you taken to debug?

**Comment by silentrob** [comment]
I'm also in the process of building the project. Is it possible to update the releases to reflect the latest API changes.

**Comment by mackorone** [comment]
@darugal were you able to get it to work?

@silentrob a [new version](https://github.com/mackorone/mms/releases/tag/v1.2.0) of the simulator is now available!
