### ISSUE TITLE
Build and run command

### ISSUE THREAD

**Issue by Svizec2010** [mackorone/mms#40]
how can i build and run in the mms, because it says process failed to start: the system cannot find the file specified. can u send me the run and build code, i looked many of yours answers but your code is not working on my pc. i have windows 11 if that would help. thanks #38

**Comment by mackorone** [comment]
Does your directory contain spaces? If so, that might be the cause of the issue. If not, what is your algorithm config?

**Comment by Svizec2010** [comment]
I am a beginner at coding (I am 14 yo)  and would need some help. I managed to solve maze coding, so now my mazes are shown in mms, but I would need some examples of build and run files. Where could I found them in your source code?
Thank you for your help.

**Comment by Svizec2010** [comment]
hi, me again...
I followed your instructions for python (mms-python) and it worked with default Main.py!!!
I see the mouse is following left turn algorithm and to my "luck" my maze is such that mouse cannot solve it with left-turn algorithm alone. Where would you suggest me to look further for other algorithms?

**Comment by mackorone** [comment]
> I couldn't find much about BUILD command...

The "build" step is only necessary for compiled languages, like C++ or Java. If you're using Python, an interpreted language, you don't need to worry about it.

> Where would you suggest me to look further for other algorithms?

Try Googling for "Micromouse Floodfill" or "Dijkstra's Algorithm". If you're not familiar with data structures like lists, graphs, stacks, queues, and heaps, you might need to learn about them first. Good luck!
