### ISSUE TITLE
Cant upload the mms sketch to arduino

### ISSUE THREAD

**Issue by ayodhyadhameesha** [mackorone/mms#7]
When I try to upload the mms sketch to arduino it shows the following error
 cannot convert 'const char*' to 'double' for argument '1' to 'double log(double)'
Can you tell me why
Thankyou

**Comment by mackorone** [comment]
Hmm, I don't recognize the `double log(double)` signature you mentioned. Where is that defined? It sounds like you're trying to pass a string to a function that takes a floating point number.

**Comment by ayodhyadhameesha** [comment]
It was in your original code I uploaded it without changing

**Comment by mackorone** [comment]
@ayodhyadhameesha, what's the file and line number of the error? Can you upload a screenshot of the error message?
