### ISSUE TITLE
can't browse the mouse

### ISSUE THREAD

**Issue by banhmithit** [mackorone/mms#8]
I can't browse the mouse to the mms
![image](https://user-images.githubusercontent.com/44237673/85204689-54310900-b340-11ea-8454-b2c448b3147b.png)
Can you make a short video to guild me?

**Comment by mackorone** [comment]
@banhmithit The "Choose Directory" dialog is for choosing a directory that contains your source code. It doesn't display files. Simply clicking "Select Folder" is fine, since `src` contains your source code.

Let me know if you have any other questions!
